"""Add website to Artist and language to Album

Revision ID: 1a5041499d7f
Revises: 39c6551c0b33
Create Date: 2024-12-28 19:33:30.904678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5041499d7f'
down_revision: Union[str, None] = '39c6551c0b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('albums', 'language')
    # ### end Alembic commands ###
