"""Add GIN index to tracks

Revision ID: 6ea7aabcf665
Revises: c169b9ae4d98
Create Date: 2024-12-29 16:24:42.757505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea7aabcf665'
down_revision: Union[str, None] = 'c169b9ae4d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_track_metadata_trgm', 'tracks', ['track_metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_track_metadata_trgm', table_name='tracks', postgresql_using='gin')
    # ### end Alembic commands ###
