"""Make album_id nullable in tracks

Revision ID: f79d3486e078
Revises: 6ea7aabcf665
Create Date: 2025-01-03 20:24:57.870439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79d3486e078'
down_revision: Union[str, None] = '6ea7aabcf665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
